version: '3'

x-environment: &global_env
  MONGO_URI: ${MONGO_URI}
  NODE_ENV: ${NODE_ENV}
  JWT_SECRET: ${JWT_SECRET}

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
  backend:
    build: .
    environment:
      <<: *global_env
    ports:
      - "5000"
    depends_on:
      - mongo
      - seed
    restart: on-failure
    # Scale the backend service to have 3 instances
    deploy:
      replicas: 3
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
    restart: on-failure
  seed:
    build:
      context: ./
      dockerfile: ./seeding-dockerfile/Dockerfile
    environment:
      <<: *global_env
    depends_on:
      - mongo
    restart: on-failure