pipeline {
    agent any
    
    stages {
        stage('Run Hello World') {
            steps {
                script {
                    sh 'docker --version'
                    
                    sh 'ls'

                    // Run hello-world Docker container
                    sh 'docker run hello-world'
                }
            }
        }
        
        // Add more stages as needed
    }
}
