pipeline {
    agent any
    
    environment {
        AWS_DEFAULT_REGION = 'eu-central-1'
        registry = credentials('ecr-registry-url')
        imageName = 'backend-repo'
        tag = 'latest'
    }
    
    stages {
        stage('Build and Tag Docker Images') {
            steps {

                sh "ls"

                sh "pwd"
                

                // Build Docker image
                sh "docker run hello-world"  
            }
        }
        
        // Add more stages as needed
    }
}
