pipeline {
    agent any
    
    environment {
        AWS_DEFAULT_REGION = 'eu-central-1'
        registry = credentials('ecr-registry-url') 
        images = [
            [name: 'backend-repo', tag: 'latest', path: ''],
            // [name: 'frontend-repo', tag: 'latest', path: 'frontend/'],
            // [name: 'db-seeding-repo', tag: 'latest', path: 'seeding-dockerfile/']
        ]
    }
    
    stages {
        stage('Build and Tag Docker Images') {
            steps {
                // Authenticate with AWS ECR
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: '96f68e7a-e3cb-4e97-97ac-472f07edf015']]) {
                    sh "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $registry"
                }
                
                // Build and tag each Docker image
                script {
                    for (def image in images) {
                        def imageName = image.name
                        def tag = image.tag
                        def path = image.path
                        
                        // Navigate to Dockerfile path
                        dir(path) {
                            // Build Docker image
                            sh "docker build -t $imageName:$tag ."
                            
                            // Tag Docker image
                            sh "docker tag $imageName:$tag $registry/$imageName:$tag"
                        }
                    }
                }
            }
        }
        
        // Add more stages as needed
    }
}
